// Générateur de seed pour 100+ styles manga
// Exécuter : deno run --allow-write database/seed-manga-100plus.ts
// Cela génère seed-manga-100plus.sql à copier dans Supabase SQL Editor

const MODEL = "'39ed52f2a78e934b3ba6e2a89f5b1c712de7dfea535525255b1aa35c5565e08b'";
const W = 1024;
const H_DEFAULT = 1024;

interface Mangaka {
  name: string;
  slug: string;
  mangaka: string;
  desc: string;
  prompt: string;
  neg: string;
  tags: string[];
  h?: number;
}

const STYLES: Mangaka[] = [
  // ═══════════════════════════════════════════
  // SHONEN — Action / Aventure
  // ═══════════════════════════════════════════
  { name: "Bleach", slug: "tite-kubo", mangaka: "Tite Kubo", desc: "Style dynamique et élégant : traits acérés, personnages stylés, poses dramatiques", prompt: "bleach manga style by tite kubo, sharp bold ink lines, {prompt}, dynamic pose, dramatic composition", neg: "photorealistic, 3d, western comic", tags: ["shonen", "action", "stylish"] },
  { name: "One Piece", slug: "eiichiro-oda", mangaka: "Eiichiro Oda", desc: "Style expressif et aventureux : proportions exagérées, visages ultra-expressifs", prompt: "one piece manga style by eiichiro oda, extremely expressive, {prompt}, bold outlines, shonen, adventure", neg: "realistic proportions, dark gritty", tags: ["shonen", "adventure", "expressive"] },
  { name: "Naruto", slug: "masashi-kishimoto", mangaka: "Masashi Kishimoto", desc: "Style ninja dynamique : coiffures distinctives, sceaux, actions de combat intenses", prompt: "naruto manga style by masashi kishimoto, dynamic ninja action, {prompt}, hand signs, strong expressions", neg: "realistic, muted colors", tags: ["shonen", "ninja", "action"] },
  { name: "Dragon Ball", slug: "akira-toriyama", mangaka: "Akira Toriyama", desc: "Style iconique : lignes nettes, personnages musclés, cheveux hérissés", prompt: "dragon ball manga style by akira toriyama, clean bold lines, muscular, {prompt}, vibrant colors, energy aura", neg: "realistic, horror, soft shading", tags: ["shonen", "martial arts", "iconic"] },
  { name: "Hunter × Hunter", slug: "yoshihiro-togashi", mangaka: "Yoshihiro Togashi", desc: "Style varié : designs uniques, textures détaillées, créatures originales", prompt: "hunter x hunter manga style by yoshihiro togashi, unique design, {prompt}, expressive, detailed textures", neg: "simple art, mecha, romantic", tags: ["shonen", "adventure", "tactical"] },
  { name: "Fullmetal Alchemist", slug: "hiromu-arakawa", mangaka: "Hiromu Arakawa", desc: "Style équilibré : personnages expressifs, design steampunk, alchimie", prompt: "fullmetal alchemist manga style by hiromu arakawa, balanced art, {prompt}, alchemy symbols, detailed backgrounds", neg: "chibi, super deformed, horror", tags: ["shonen", "fantasy", "steampunk"] },
  { name: "Attack on Titan", slug: "hajime-iseyama", mangaka: "Hajime Isayama", desc: "Style brut et intense : traits rugueux, proportions massives, ombres marquées", prompt: "attack on titan manga style by hajime isayama, rough detailed lines, {prompt}, massive scale, intense expressions, dark mood", neg: "clean lines, cute, cheerful", tags: ["shonen", "dark fantasy", "intense"] },
  { name: "My Hero Academia", slug: "kohei-horikoshi", mangaka: "Kohei Horikoshi", desc: "Style superhero moderne : designs dynamiques, pouvoirs colorés, expressions exagérées", prompt: "my hero academia manga style by kohei horikoshi, superhero dynamic, {prompt}, vibrant powers, character design", neg: "realistic proportions, dark", tags: ["shonen", "superhero", "dynamic"] },
  { name: "Demon Slayer", slug: "koyoharu-gotouge", mangaka: "Koyoharu Gotouge", desc: "Style élégant et tranchant : motifs japonais, lignes fluides, effets d'eau", prompt: "demon slayer manga style by koyoharu gotouge, elegant sharp lines, {prompt}, water effects, taisho era, detailed eyes", neg: "western comic, photorealistic", tags: ["shonen", "historical", "elegant"] },
  { name: "Jujutsu Kaisen", slug: "gege-akutami", mangaka: "Gege Akutami", desc: "Style sombre et technique : designs modernes, cursed energy, combats tactiques", prompt: "jujutsu kaisen manga style by gege akutami, dark modern art, {prompt}, cursed energy effects, tactical combat", neg: "bright colors, simple", tags: ["shonen", "dark", "tactical"] },
  { name: "One Punch Man", slug: "yusuke-murata", mangaka: "Yusuke Murata", desc: "Style ultra-détaillé : traits précis, musculature, effets de choc spectaculaires", prompt: "one punch man manga style by yusuke murata, incredibly detailed, {prompt}, dynamic action lines, impact frames", neg: "simple art, rough sketch", tags: ["shonen", "detailed", "action"] },
  { name: "JoJo's Bizarre Adventure", slug: "hirohiko-araki", mangaka: "Hirohiko Araki", desc: "Style flamboyant et musclé : poses iconiques, designs de mode, stands", prompt: "jojo bizarre adventure manga style by hirohiko araki, muscular characters, {prompt}, iconic pose, fashion design, stand powers", neg: "realistic proportions, plain", tags: ["shonen", "flamboyant", "iconic"] },
  { name: "Fairy Tail", slug: "hiro-mashima", mangaka: "Hiro Mashima", desc: "Style lumineux et dynamique : personnages expressifs, magie colorée", prompt: "fairy tail manga style by hiro mashima, bright expressive, {prompt}, magic effects, guild marks, friendship", neg: "dark, horror, realistic", tags: ["shonen", "fantasy", "bright"] },
  { name: "Black Clover", slug: "yuki-tabata", mangaka: "Yuki Tabata", desc: "Style énergique : grimoires, magie noire, designs médiévaux", prompt: "black clover manga style by yuki tabata, grimoire magic, {prompt}, medieval fantasy, energetic art", neg: "modern setting, sci-fi", tags: ["shonen", "fantasy", "magic"] },
  { name: "Magi", slug: "shinobu-otaka", mangaka: "Shinobu Ohtaka", desc: "Style des mille et une nuits : design arabesques, magie, aventure épique", prompt: "magi manga style by shinobu ohtaka, arabesque design, {prompt}, magical, fantasy adventure, detailed costumes", neg: "modern, sci-fi", tags: ["shonen", "fantasy", "arabian"] },
  { name: "Soul Eater", slug: "atsushi-ohkubo", mangaka: "Atsushi Ohkubo", desc: "Style distinctif et excentrique : designs uniques, lignes anguleuses, crânes", prompt: "soul eater manga style by atsushi ohkubo, distinctive sharp art, {prompt}, meister, weapon transformation, gothic", neg: "realistic, cute", tags: ["shonen", "gothic", "unique"] },
  { name: "D.Gray-man", slug: "katsura-hoshino", mangaka: "Katsura Hoshino", desc: "Style gothique détaillé : designs élaborés, akuma, ambiance sombre", prompt: "d gray man manga style by katsura hoshino, gothic detailed, {prompt}, akuma, innocence, dark Victorian", neg: "bright, simple, chibi", tags: ["shonen", "gothic", "dark"] },
  { name: "Gintama", slug: "hideaki-sorachi", mangaka: "Hideaki Sorachi", desc: "Style comique et fou : expressions absurdes, parodies, action déjantée", prompt: "gintama manga style by hideaki sorachi, comedic expressive, {prompt}, parody, absurd humor, samurai", neg: "serious, realistic", tags: ["shonen", "comedy", "parody"] },
  { name: "Rurouni Kenshin", slug: "nobuhiro-watsuki", mangaka: "Nobuhiro Watsuki", desc: "Style samouraï classique : traits élégants, ère Meiji, combat au sabre", prompt: "rurouni kenshin manga style by nobuhiro watsuki, elegant samurai art, {prompt}, meiji era, battousai, sword fighting", neg: "modern, sci-fi", tags: ["shonen", "historical", "samurai"] },
  { name: "Yu Yu Hakusho", slug: "yoshihiro-togashi-2", mangaka: "Yoshihiro Togashi", desc: "Style combat spirituel : énergie spirituelle, démons, arts martiaux", prompt: "yu yu hakusho manga style by yoshihiro togashi, spirit energy, {prompt}, demon world, martial arts, 90s shonen", neg: "modern digital art", tags: ["shonen", "spiritual", "martial arts"] },
  { name: "Katekyo Hitman Reborn", slug: "akira-amano", mangaka: "Akira Amano", desc: "Style mafia élégant : costumes italiens, flammes, designs stylisés", prompt: "katekyo hitman reborn manga style by akira amano, mafia elegant, {prompt}, dying will flames, vongola, stylish", neg: "plain, realistic", tags: ["shonen", "mafia", "stylish"] },
  { name: "Toriko", slug: "mitsutoshi-shimabukuro", mangaka: "Mitsutoshi Shimabukuro", desc: "Style gastronomique sauvage : creatures détaillées, nourriture, muscles", prompt: "toriko manga style by mitsutoshi shimabukuro, gourmet hunting, {prompt}, detailed creatures, muscular, food", neg: "slim characters, quiet", tags: ["shonen", "adventure", "food"] },
  { name: "Beelzebub", slug: "ryuhei-tamura", mangaka: "Ryuhei Tamura", desc: "Style démoniaque comique : bébé démon, combat délirant, école", prompt: "beelzebub manga style by ryuhei tamura, demon comedy, {prompt}, baby demon, delinquent school, over the top", neg: "serious, realistic", tags: ["shonen", "comedy", "demons"] },
  { name: "World Trigger", slug: "daisuke-ashihara", mangaka: "Daisuke Ashihara", desc: "Style tactique : designs épurés, combats stratégiques, aliens", prompt: "world trigger manga style by daisuke ashihara, tactical clean art, {prompt}, trigger weapons, neighbor, strategic combat", neg: "messy lines, horror", tags: ["shonen", "tactical", "sci-fi"] },
  { name: "The Seven Deadly Sins", slug: "nakaba-suzuki", mangaka: "Nakaba Suzuki", desc: "Style médiéval heroic fantasy : designs inspirés du Roi Arthur", prompt: "seven deadly sins manga style by nakaba suzuki, medieval fantasy, {prompt}, holy knights, britannia, sacred treasures", neg: "modern, sci-fi", tags: ["shonen", "fantasy", "medieval"] },
  { name: "Radiant", slug: "tony-valente", mangaka: "Tony Valente", desc: "Style fantasy français : sorciers, nemesis, aventure, designs inspirés", prompt: "radiant manga style by tony valente, french manga, {prompt}, sorcerer, nemesis, fantasia, adventurous", neg: "realistic, traditional japanese", tags: ["shonen", "fantasy", "french"] },

  // ═══════════════════════════════════════════
  // SEINEN — Adulte / Mature
  // ═══════════════════════════════════════════
  { name: "Berserk", slug: "kentaro-miura", mangaka: "Kentaro Miura", desc: "Style sombre et ultra-détaillé : hachures croisées, médiéval gothique, tragique", prompt: "berserk manga style by kentaro miura, incredibly detailed cross-hatching, dark medieval fantasy, {prompt}, heavy ink work", neg: "bright colors, cartoon, chibi", tags: ["seinen", "dark fantasy", "detailed"], h: 768 },
  { name: "Vagabond", slug: "takehiko-inoue", mangaka: "Takehiko Inoue", desc: "Style sumi-e : encrage au pinceau, philosophie zen, samouraï", prompt: "vagabond manga style by takehiko inoue, brush ink art, {prompt}, samurai, zen, philosophical, sumi-e painting", neg: "digital art, bright colors", tags: ["seinen", "historical", "philosophical"], h: 768 },
  { name: "Monster", slug: "naoki-urasawa", mangaka: "Naoki Urasawa", desc: "Style réaliste et précis : designs authentiques, suspense psychologique", prompt: "monster manga style by naoki urasawa, realistic detailed art, {prompt}, psychological thriller, 1990s germany, tense", neg: "fantasy, superhero, cartoon", tags: ["seinen", "psychological", "realistic"] },
  { name: "20th Century Boys", slug: "naoki-urasawa-2", mangaka: "Naoki Urasawa", desc: "Style mystérieux : amitié d'enfance, conspiration, nostalgie 70s", prompt: "20th century boys manga style by naoki urasawa, nostalgic detailed, {prompt}, conspiracy, childhood friends, 1970s japan", neg: "fantasy, sci-fi", tags: ["seinen", "mystery", "nostalgic"] },
  { name: "Pluto", slug: "naoki-urasawa-3", mangaka: "Naoki Urasawa", desc: "Style robotique : détective, androïdes, Astro Boy revisité", prompt: "pluto manga style by naoki urasawa, robotic detailed, {prompt}, detective, android, futuristic noir", neg: "cartoon, chibi", tags: ["seinen", "sci-fi", "mystery"] },
  { name: "Kingdom", slug: "yasuhisa-hara", mangaka: "Yasuhisa Hara", desc: "Style guerre antique : batailles épiques, Chine des Royaumes combattants", prompt: "kingdom manga style by yasuhisa hara, epic war art, {prompt}, ancient china, battlefield, generals, tactical warfare", neg: "modern, fantasy", tags: ["seinen", "historical", "war"], h: 768 },
  { name: "Vinland Saga", slug: "makoto-yukimura", mangaka: "Makoto Yukimura", desc: "Style viking épique : designs historiques, batailles, philosophie", prompt: "vinland saga manga style by makoto yukimura, viking art, {prompt}, norse, historical, epic battles, detailed armor", neg: "fantasy, cartoon", tags: ["seinen", "historical", "viking"], h: 768 },
  { name: "Tokyo Ghoul", slug: "sui-ishida", mangaka: "Sui Ishida", desc: "Style sombre et tourmenté : ghouls, dessins détaillés, ambiance urbaine", prompt: "tokyo ghoul manga style by sui ishida, dark detailed art, {prompt}, ghoul, kagune, urban dark, psychological", neg: "bright colors, simple", tags: ["seinen", "dark", "psychological"] },
  { name: "Parasyte", slug: "hitoshi-iwaaki", mangaka: "Hitoshi Iwaaki", desc: "Style horrifique organique : transformations corporelles, aliens", prompt: "parasyte manga style by hitoshi iwaaki, organic horror, {prompt}, body horror, alien parasite, detailed transformations", neg: "cartoon, cute", tags: ["seinen", "horror", "sci-fi"] },
  { name: "Blade of the Immortal", slug: "hiroaki-samoura", mangaka: "Hiroaki Samura", desc: "Style sabre japonais : encrage expressif, combat au katana, immortel", prompt: "blade of the immortal manga style by hiroaki samura, expressive ink, {prompt}, samurai, immortal, bloody combat", neg: "digital glossy, bright", tags: ["seinen", "historical", "samurai"], h: 768 },
  { name: "Lone Wolf and Cub", slug: "kazuo-koike", mangaka: "Kazuo Koike", desc: "Style classique : samouraï errant, enfant, vengeance, période Edo", prompt: "lone wolf and cub manga style by kazuo koike, classic samurai art, {prompt}, ronin, baby cart, edo period, vengeance", neg: "modern, fantasy", tags: ["seinen", "historical", "classic"], h: 768 },
  { name: "Battle Angel Alita", slug: "yukito-kishiro", mangaka: "Yukito Kishiro", desc: "Style cyberpunk : cyborgs, combat, designs mécaniques détaillés", prompt: "battle angel alita manga style by yukito kishiro, cyberpunk detailed, {prompt}, cyborg, gunnm, motorball, futuristic", neg: "fantasy, historical", tags: ["seinen", "cyberpunk", "sci-fi"] },
  { name: "Gantz", slug: "hiroya-oku", mangaka: "Hiroya Oku", desc: "Style 3D brut : aliens, survie, combats graphiques et violents", prompt: "gantz manga style by hiroya oku, graphic violent, {prompt}, alien hunting, gantz suit, survival, detailed gore", neg: "cute, children", tags: ["seinen", "sci-fi", "violent"] },
  { name: "Homunculus", slug: "hideo-yamamoto", mangaka: "Hideo Yamamoto", desc: "Style psychologique expérimental : noir et blanc, introspection", prompt: "homunculus manga style by hideo yamamoto, experimental art, {prompt}, psychological, black and white, introspective", neg: "colorful, action", tags: ["seinen", "psychological", "experimental"] },
  { name: "Ichi the Killer", slug: "hideo-yamamoto-2", mangaka: "Hideo Yamamoto", desc: "Style yakuza violent : underground, gore, psychologique", prompt: "ichi the killer manga style by hideo yamamoto, yakuza violent, {prompt}, underground, psychological, graphic", neg: "mainstream, cute", tags: ["seinen", "violent", "underground"] },
  { name: "The Fable", slug: "katsuhisa-minami", mangaka: "Katsuhisa Minami", desc: "Style assassin décontracté : humour noir, action, quotidien", prompt: "the fable manga style by katsuhisa minami, hitman comedy, {prompt}, assassin, daily life, dark humor, osaka", neg: "fantasy, sci-fi", tags: ["seinen", "comedy", "action"] },
  { name: "Sun-Ken Rock", slug: "boichi", mangaka: "Boichi", desc: "Style coréen détaillé : muscles, action, designs réalistes", prompt: "sun ken rock manga style by boichi, detailed korean art, {prompt}, muscular, gangster, action intense, realistic", neg: "chibi, simple", tags: ["seinen", "action", "detailed"] },
  { name: "Dr. Stone", slug: "boichi-2", mangaka: "Boichi", desc: "Style scientifique : designs précis, monde de pierre, aventure", prompt: "dr stone manga style by boichi, scientific detailed, {prompt}, stone world, science, invention, senku", neg: "fantasy, magic", tags: ["shonen", "sci-fi", "scientific"] },
  { name: "Origin", slug: "boichi-3", mangaka: "Boichi", desc: "Style robotique futuriste : combat, designs mécaniques, technologique", prompt: "origin manga style by boichi, futuristic robotic, {prompt}, mecha, android, detailed machinery, cyberpunk", neg: "fantasy, medieval", tags: ["seinen", "sci-fi", "mecha"] },
  { name: "Ajin", slug: "gamon-sakurai", mangaka: "Gamon Sakurai", desc: "Style 3D minimaliste : immortels, IBM noirs, poursuites", prompt: "ajin manga style by gamon sakurai, minimal 3d art, {prompt}, demi-human, ibm, black ghost, pursuit", neg: "bright, colorful", tags: ["seinen", "sci-fi", "minimalist"] },

  // ═══════════════════════════════════════════
  // SHOJO — Romance / Émotion
  // ═══════════════════════════════════════════
  { name: "Fruits Basket", slug: "natsuki-takaya", mangaka: "Natsuki Takaya", desc: "Style shojo doux : personnages ronds, transformation animale, émotion", prompt: "fruits basket manga style by natsuki takaya, soft shojo art, {prompt}, animal transformation, emotional, warm", neg: "dark, action, horror", tags: ["shojo", "romance", "fantasy"] },
  { name: "Sailor Moon", slug: "naoko-takeuchi", mangaka: "Naoko Takeuchi", desc: "Style magical girl iconique : costumes, transformations, combat", prompt: "sailor moon manga style by naoko takeuchi, magical girl, {prompt}, sailor suit, transformation, lunar, 90s shojo", neg: "dark, realistic", tags: ["shojo", "magical girl", "iconic"] },
  { name: "Cardcaptor Sakura", slug: "clamp-cs", mangaka: "CLAMP", desc: "Style magical girl élégant : costumes détaillés, cartes, pureté", prompt: "cardcaptor sakura manga style by clamp, magical girl elegant, {prompt}, clow cards, sakura, detailed costumes, cute", neg: "dark, violent", tags: ["shojo", "magical girl", "elegant"] },
  { name: "Nana", slug: "ai-yazawa", mangaka: "Ai Yazawa", desc: "Style mode réaliste : designs vestimentaires, vie urbaine, rock", prompt: "nana manga style by ai yazawa, fashion realistic, {prompt}, punk rock, urban life, detailed clothing, emotional", neg: "fantasy, action", tags: ["shojo", "drama", "fashion"] },
  { name: "Ouran High School Host Club", slug: "bisco-hatori", mangaka: "Bisco Hatori", desc: "Style comédie romantique : hôtes, école luxueuse, parodie shojo", prompt: "ouran high school host club manga style by bisco hatori, romantic comedy, {prompt}, host club, school, elegant comedy", neg: "dark, serious", tags: ["shojo", "comedy", "romance"] },
  { name: "Kimi ni Todoke", slug: "karuho-shiina", mangaka: "Karuho Shiina", desc: "Style doux et pur : romance scolaire, malentendus, amitié", prompt: "kimi ni todoke manga style by karuho shiina, soft pure art, {prompt}, school romance, sawako, shy love", neg: "dark, action", tags: ["shojo", "romance", "school"] },
  { name: "Vampire Knight", slug: "matsuri-hino", mangaka: "Matsuri Hino", desc: "Style gothique romantique : vampires, école, triangle amoureux", prompt: "vampire knight manga style by matsuri hino, gothic romance, {prompt}, vampire, night class, moonlight, dark elegant", neg: "bright, comedy", tags: ["shojo", "romance", "vampire"] },
  { name: "Skip Beat", slug: "yoshiki-nakamura", mangaka: "Yoshiki Nakamura", desc: "Style showbiz : actrice, revanche, romance, industrie du divertissement", prompt: "skip beat manga style by yoshiki nakamura, showbiz art, {prompt}, actress, show business, revenge, entertainment", neg: "fantasy, historical", tags: ["shojo", "drama", "showbiz"] },
  { name: "Kaichou wa Maid-sama", slug: "hiro-fujiwara", mangaka: "Hiro Fujiwara", desc: "Style comédie scolaire : présidente, maid café, romance", prompt: "kaichou wa maid sama manga style by hiro fujiwara, school comedy, {prompt}, student council, maid cafe, tsundere", neg: "dark, serious", tags: ["shojo", "comedy", "school"] },
  { name: "Ao Haru Ride", slug: "io-sakisaka", mangaka: "Io Sakisaka", desc: "Style romance nostalgique : amour de jeunesse, retrouvailles", prompt: "ao haru ride manga style by io sakisaka, nostalgic youth, {prompt}, high school romance, summer, reunion", neg: "fantasy, action", tags: ["shojo", "romance", "nostalgic"] },
  { name: "Orange", slug: "ichigo-takano", mangaka: "Ichigo Takano", desc: "Style émotionnel : lettres du futur, regret, amitié", prompt: "orange manga style by ichigo takano, emotional art, {prompt}, letters from future, friendship, regret, hope", neg: "action, violent", tags: ["shojo", "drama", "emotional"] },
  { name: "Yona of the Dawn", slug: "mizuho-kusanagi", mangaka: "Mizuho Kusanagi", desc: "Style fantasy shojo : princesse, dragons, aventure épique", prompt: "yona of the dawn manga style by mizuho kusanagi, fantasy shojo, {prompt}, princess, four dragons, kouka kingdom", neg: "modern, sci-fi", tags: ["shojo", "fantasy", "adventure"] },
  { name: "Kamisama Kiss", slug: "julietta-suzuki", mangaka: "Julietta Suzuki", desc: "Style divin : dieux, esprits, romance surnaturelle, comédie", prompt: "kamisama kiss manga style by julietta suzuki, divine romance, {prompt}, fox familiar, shrine maiden, supernatural", neg: "horror, gore", tags: ["shojo", "romance", "supernatural"] },

  // ═══════════════════════════════════════════
  // HORREUR
  // ═══════════════════════════════════════════
  { name: "Junji Ito", slug: "junji-ito", mangaka: "Junji Ito", desc: "Style horrifique méticuleux : détails obsessionnels, spirales, beauté mêlée d'effroi", prompt: "junji ito manga art style, meticulous detail, unsettling horror, {prompt}, intricate spiral patterns, body horror", neg: "happy, bright colors, cute", tags: ["horror", "psychological", "detailed"], h: 768 },
  { name: "Uzumaki", slug: "junji-ito-uzumaki", mangaka: "Junji Ito", desc: "Style spirales obsessionnelles : motifs de spirale, folie, malédiction", prompt: "uzumaki manga by junji ito, spiral obsession, {prompt}, spiral patterns, curse, madness, body distortion", neg: "normal, bright", tags: ["horror", "psychological", "spiral"], h: 768 },
  { name: "Tomie", slug: "junji-ito-tomie", mangaka: "Junji Ito", desc: "Style beauté fatale : femme immortelle, horreur psychologique", prompt: "tomie manga by junji ito, beautiful horror, {prompt}, immortal woman, psychological horror, obsession", neg: "normal proportions", tags: ["horror", "psychological", "beautiful"], h: 768 },
  { name: "Hellstar Remina", slug: "junji-ito-rem", mangaka: "Junji Ito", desc: "Style horreur cosmique : planète vivante, fin du monde, désespoir", prompt: "hellstar remina manga by junji ito, cosmic horror, {prompt}, living planet, apocalypse, despair, vast scale", neg: "hope, bright", tags: ["horror", "cosmic", "apocalyptic"], h: 768 },
  { name: "The Enigma of Amigara Fault", slug: "junji-ito-amigara", mangaka: "Junji Ito", desc: "Style horreur existentielle : failles, corps humains, obsession", prompt: "enigma of amigara fault manga by junji ito, existential horror, {prompt}, fault line, human shape holes, compulsion", neg: "normal, bright", tags: ["horror", "existential", "disturbing"], h: 768 },
  { name: "Another", slug: "yukito-ayatsuji", mangaka: "Yukito Ayatsuji", desc: "Style horreur scolaire : malédiction, classe maudite, suspense", prompt: "another manga style by yukito ayatsuji, school horror, {prompt}, cursed class, suspense, eerie atmosphere, 1998", neg: "action, comedy", tags: ["horror", "school", "suspense"] },
  { name: "Corpse Party", slug: "mikoto-akira", mangaka: "Makoto Kedouin", desc: "Style horreur survival : école hantée, morts violentes, sang", prompt: "corpse party manga style, school horror gore, {prompt}, haunted school, violent death, blood, despair", neg: "happy, colorful", tags: ["horror", "survival", "gore"] },
  { name: "Higurashi", slug: "ryukishi07", mangaka: "Ryukishi07", desc: "Style horreur mystère : village, malédiction, boucle temporelle", prompt: "higurashi manga style by ryukishi07, mystery horror, {prompt}, cursed village, time loop, moe horror", neg: "simple moe, bright", tags: ["horror", "mystery", "psychological"] },
  { name: "Shiki", slug: "fuyumi-ono", mangaka: "Fuyumi Ono", desc: "Style horreur vampires : village isolé, invasion, survie", prompt: "shiki manga style by fuyumi ono, vampire horror, {prompt}, isolated village, night invasion, survival horror", neg: "action, bright", tags: ["horror", "vampire", "survival"] },

  // ═══════════════════════════════════════════
  // SLICE OF LIFE — Quotidien
  // ═══════════════════════════════════════════
  { name: "Yotsuba", slug: "kiyohiko-azuma", mangaka: "Kiyohiko Azuma", desc: "Style quotidien pur : enfant, découvertes, bonheur simple", prompt: "yotsuba manga style by kiyohiko azuma, slice of life, {prompt}, yotsuba, everyday adventures, simple clean art", neg: "dark, action, fantasy", tags: ["slice of life", "comedy", "cute"] },
  { name: "Azumanga Daioh", slug: "kiyohiko-azuma-2", mangaka: "Kiyohiko Azuma", desc: "Style école comique : lycéennes, quotidien déjanté, amitié", prompt: "azumanga daioh manga style by kiyohiko azuma, school comedy, {prompt}, high school girls, daily life, quirky", neg: "dark, serious", tags: ["slice of life", "comedy", "school"] },
  { name: "Barakamon", slug: "satsuki-yoshino", mangaka: "Satsuki Yoshino", desc: "Style calligraphie : île, calligraphe, habitants, vie simple", prompt: "barakamon manga style by satsuki yoshino, island life, {prompt}, calligraphy, countryside, simple life, heartwarming", neg: "dark, urban", tags: ["slice of life", "comedy", "heartwarming"] },
  { name: "Non Non Biyori", slug: "atto", mangaka: "Atto", desc: "Style campagne : école rurale, nature, enfants, saisons", prompt: "non non biyori manga style by atto, rural countryside, {prompt}, school, nature, seasons, slow life", neg: "city, action", tags: ["slice of life", "countryside", "cute"] },
  { name: "Flying Witch", slug: "chihiro-ishizuka", mangaka: "Chihiro Ishizuka", desc: "Style sorcellerie douce : witch, campagne, magie quotidienne", prompt: "flying witch manga style by chihiro ishizuka, gentle magic, {prompt}, witch, countryside, everyday magic, cozy", neg: "dark, action", tags: ["slice of life", "fantasy", "cozy"] },
  { name: "March Comes in Like a Lion", slug: "chika-umino", mangaka: "Chika Umino", desc: "Style shogi émotionnel : joueur pro, dépression, famille", prompt: "sangatsu no lion manga style by chika umino, emotional art, {prompt}, shogi, depression, family, warmth", neg: "action, fantasy", tags: ["slice of life", "drama", "emotional"] },
  { name: "Honey and Clover", slug: "chika-umino-2", mangaka: "Chika Umino", desc: "Style vie étudiante : beaux-arts, amour, amitié, incertitude", prompt: "honey and clover manga style by chika umino, art student life, {prompt}, college, romance, friendship, uncertainty", neg: "fantasy, action", tags: ["slice of life", "romance", "college"] },
  { name: "Mushishi", slug: "yuki-urshihama", mangaka: "Yuki Urushibara", desc: "Style nature mystique : esprits, voyageur, campagne japonaise", prompt: "mushishi manga style by yuki urushibara, mystical nature, {prompt}, mushi, traveling, rural japan, ethereal", neg: "urban, modern", tags: ["slice of life", "supernatural", "mystical"] },
  { name: "Aria", slug: "kozue-amanu", mangaka: "Kozue Amano", desc: "Style neo-Venise : gondoles, aqua, guide touristique, détente", prompt: "aria manga style by kozue amano, neo venice, {prompt}, gondola, undine, aqua, relaxing atmosphere", neg: "dark, action", tags: ["slice of life", "scifi", "relaxing"] },
  { name: "Yokohama Kaidashi Kikou", slug: "hitoshi-ashinano", mangaka: "Hitoshi Ashinano", desc: "Style post-apo paisible : café, robot, monde calme après la fin", prompt: "yokohama kaidashi kikou manga style by hitoshi ashinano, post-apocalyptic peaceful, {prompt}, cafe, robot, quiet world", neg: "action, violence", tags: ["slice of life", "post-apocalyptic", "peaceful"] },

  // ═══════════════════════════════════════════
  // MECHA / SCI-FI
  // ═══════════════════════════════════════════
  { name: "Neon Genesis Evangelion", slug: "yoshiyuki-sadamoto", mangaka: "Yoshiyuki Sadamoto", desc: "Style mecha psychologique : robots, anges, trauma, apocalypse", prompt: "evangelion manga style by yoshiyuki sadamoto, mecha psychological, {prompt}, evangelion, angel, plug suit, instrumentality", neg: "bright, simple, comedy", tags: ["sci-fi", "mecha", "psychological"] },
  { name: "Akira", slug: "katsuhiro-otomo", mangaka: "Katsuhiro Otomo", desc: "Style cyberpunk détaillé : motos, télékinésie, méga-city, révolution", prompt: "akira manga style by katsuhiro otomo, cyberpunk detailed, {prompt}, neo tokyo, motorcycle, psychic powers, rebellion", neg: "fantasy, medieval", tags: ["sci-fi", "cyberpunk", "classic"], h: 768 },
  { name: "Ghost in the Shell", slug: "masamune-shirow", mangaka: "Masamune Shirow", desc: "Style cyberpunk réaliste : cyborgs, hacking, philosophie", prompt: "ghost in the shell manga style by masamune shirow, cyberpunk realistic, {prompt}, cyborg, section 9, hacking, philosophical", neg: "fantasy, cartoon", tags: ["sci-fi", "cyberpunk", "philosophical"] },
  { name: "Gundam", slug: "yoshiyuki-tomino", mangaka: "Yoshiyuki Tomino", desc: "Style mecha réaliste : robots géants, guerre spatiale, politique", prompt: "gundam manga style by yoshiyuki tomino, mecha realistic, {prompt}, mobile suit, space war, uc timeline, political", neg: "fantasy, comedy", tags: ["sci-fi", "mecha", "war"] },
  { name: "Gurren Lagann", slug: "kotaro-mori", mangaka: "Kotaro Mori", desc: "Style mecha exagéré : perce le ciel, combat épique, volonté", prompt: "gurren lagann manga style by kotaro mori, over the top mecha, {prompt}, drills, spiral energy, epic scale, willpower", neg: "realistic, small scale", tags: ["sci-fi", "mecha", "epic"] },
  { name: "Code Geass", slug: "clamp-cg", mangaka: "CLAMP", desc: "Style mecha politique : designs CLAMP, chevaliers, stratégie", prompt: "code geass manga style by clamp, political mecha, {prompt}, knightmare frame, geass, strategic, zero", neg: "simple, chibi", tags: ["sci-fi", "mecha", "political"] },
  { name: "Planetes", slug: "makoto-yukimura-2", mangaka: "Makoto Yukimura", desc: "Style spatial réaliste : astronautes, débris, vie en orbite", prompt: "planetes manga style by makoto yukimura, realistic space, {prompt}, astronaut, debris collector, orbital life, hard sci-fi", neg: "fantasy, magic", tags: ["sci-fi", "realistic", "space"] },
  { name: "Space Battleship Yamato", slug: "leiji-matsumoto", mangaka: "Leiji Matsumoto", desc: "Style space opera classique : vaisseau, voyage interstellaire", prompt: "space battleship yamato manga style by leiji matsumoto, classic space opera, {prompt}, yamato, interstellar, 70s anime style", neg: "modern digital", tags: ["sci-fi", "space opera", "classic"] },

  // ═══════════════════════════════════════════
  // FANTASY — Isekai / Aventure
  // ═══════════════════════════════════════════
  { name: "CLAMP", slug: "clamp", mangaka: "CLAMP", desc: "Style élégant et raffiné : longs membres, costumes détaillés, onirique", prompt: "clamp manga art style, elegant character design, long flowing limbs, {prompt}, delicate linework, shojo", neg: "rough sketch, thick lines", tags: ["shojo", "elegant", "fantasy"] },
  { name: "Tsubasa Reservoir Chronicle", slug: "clamp-trc", mangaka: "CLAMP", desc: "Style multivers : voyage entre mondes, aventure, magie", prompt: "tsubasa reservoir chronicle manga style by clamp, multiverse adventure, {prompt}, feather, dimension travel, magical", neg: "simple, plain", tags: ["fantasy", "adventure", "multiverse"] },
  { name: "xxxHOLiC", slug: "clamp-holic", mangaka: "CLAMP", desc: "Style mystique : magie, esprits, souhaits, design élaboré", prompt: "xxxholic manga style by clamp, mystical elegant, {prompt}, witch, spirits, wish granting, kimono, surreal", neg: "modern, simple", tags: ["fantasy", "supernatural", "mystical"] },
  { name: "Made in Abyss", slug: "akihito-tsukushi", mangaka: "Akihito Tsukushi", desc: "Style aventure dangereuse : abysse, créatures, exploration", prompt: "made in abyss manga style by akihito tsukushi, abyss adventure, {prompt}, deep hole, creatures, curse, exploration", neg: "bright happy", tags: ["fantasy", "adventure", "dark"] },
  { name: "Re:Zero", slug: "daichi-matsuse", mangaka: "Daichi Matsuse", desc: "Style isekai sombre : retour par la mort, fantasy, souffrance", prompt: "re zero manga style, isekai dark fantasy, {prompt}, return by death, subaru, emilia, witch cult, suffering", neg: "comedy, bright", tags: ["fantasy", "isekai", "dark"] },
  { name: "Overlord", slug: "so-bin", mangaka: "So-bin", desc: "Style isekai sombre : squelette, armée, conquête, fantasy", prompt: "overlord manga style by so-bin, dark isekai, {prompt}, skeleton overlord, nazarick, undead, conquest", neg: "bright, comedy", tags: ["fantasy", "isekai", "dark"] },
  { name: "The Ancient Magus Bride", slug: "kore-yamazaki", mangaka: "Kore Yamazaki", desc: "Style fantasy celtique : magie, fae, Angleterre, romance", prompt: "ancient magus bride manga style by kore yamazaki, celtic fantasy, {prompt}, mage, fae, england, magical creatures", neg: "modern, sci-fi", tags: ["fantasy", "romance", "celtic"] },
  { name: "Sword Art Online", slug: "abec", mangaka: "abec", desc: "Style isekai game : VRMMO, épées, niveaux, romance", prompt: "sword art online manga style by abec, vrmmo fantasy, {prompt}, sword skills, alfheim, kirito, asuna", neg: "horror, gore", tags: ["fantasy", "isekai", "game"] },
  { name: "MagiLumiere", slug: "sekka-iwata", mangaka: "Sekka Iwata", desc: "Style magical girl moderne : sorcières, contrats, entreprise", prompt: "magilumiere manga style by sekka iwata, magical girl modern, {prompt}, witch company, contract, corporate magic", neg: "classic magical girl", tags: ["fantasy", "magical girl", "modern"] },
  { name: "Delicious in Dungeon", slug: "ryoko-kui", mangaka: "Ryoko Kui", desc: "Style cuisine fantasy : donjon, monstres, recettes, aventure", prompt: "delicious in dungeon manga style by ryoko kui, dungeon cooking, {prompt}, monster cuisine, adventurers, recipes, fantasy food", neg: "modern, scary", tags: ["fantasy", "comedy", "food"] },

  // ═══════════════════════════════════════════
  // SPORTS
  // ═══════════════════════════════════════════
  { name: "Slam Dunk", slug: "takehiko-inoue-sd", mangaka: "Takehiko Inoue", desc: "Style basket dynamique : action, muscles, 90s, passion", prompt: "slam dunk manga style by takehiko inoue, basketball dynamic, {prompt}, shohoku, slam dunk, 90s sports, intense match", neg: "fantasy, chibi", tags: ["sports", "basketball", "classic"] },
  { name: "Haikyuu", slug: "haruichi-furudate", mangaka: "Haruichi Furudate", desc: "Style volley-ball explosif : sauts, réceptions, esprit d'équipe", prompt: "haikyuu manga style by haruichi furudate, volleyball dynamic, {prompt}, spike, receive, karasuno, team spirit", neg: "fantasy, horror", tags: ["sports", "volleyball", "dynamic"] },
  { name: "Kuroko's Basketball", slug: "tadatoshi-fujimaki", mangaka: "Tadatoshi Fujimaki", desc: "Style basket surnaturel : génération miracle, techniques spéciales", prompt: "kuroko basketball manga style by tadatoshi fujimaki, super basketball, {prompt}, generation of miracles, seirin, special moves", neg: "realistic sports", tags: ["sports", "basketball", "supernatural"] },
  { name: "Eyeshield 21", slug: "yuusuke-murata-2", mangaka: "Yusuke Murata", desc: "Style football américain : muscles, courses, tactiques", prompt: "eyeshield 21 manga style by yusuke murata, american football, {prompt}, devil bats, sena, powerful runs, tactical", neg: "fantasy, chibi", tags: ["sports", "football", "action"] },
  { name: "Hajime no Ippo", slug: "george-morikawa", mangaka: "George Morikawa", desc: "Style boxe réaliste : combat, entraînement, dépassement de soi", prompt: "hajime no ippo manga style by george morikawa, boxing realistic, {prompt}, ippo, punch, training, comeback, dempsey roll", neg: "fantasy, supernatural", tags: ["sports", "boxing", "realistic"] },
  { name: "Captain Tsubasa", slug: "yoichi-takahashi", mangaka: "Yoichi Takahashi", desc: "Style foot classique : tirs puissants, gardiens, tournois", prompt: "captain tsubasa manga style by yoichi takahashi, soccer classic, {prompt}, drive shot, genzo, tournament, team play", neg: "realistic proportions", tags: ["sports", "soccer", "classic"] },
  { name: "Prince of Tennis", slug: "takeshi-konomi", mangaka: "Takeshi Konomi", desc: "Style tennis technique : super coups, prodige, compétition", prompt: "prince of tennis manga style by takeshi konomi, tennis technical, {prompt}, echizen, special shots, seigaku, tournament", neg: "fantasy, horror", tags: ["sports", "tennis", "technical"] },
  { name: "Yowamushi Pedal", slug: "wataru-watanabe", mangaka: "Wataru Watanabe", desc: "Style cyclisme : course, gravats, grimpeur, endurance", prompt: "yowamushi pedal manga style by wataru watanabe, cycling racing, {prompt}, onoda, hill climb, inter-high, bicycle", neg: "fantasy, action", tags: ["sports", "cycling", "endurance"] },
  { name: "Baby Steps", slug: "hikaru-katsuki", mangaka: "Hikaru Katsuki", desc: "Style tennis réaliste : progression, entraînement, stratégie", prompt: "baby steps manga style by hikaru katsuki, realistic tennis, {prompt}, practice, strategy, improvement, technique", neg: "supernatural, action", tags: ["sports", "tennis", "realistic"] },

  // ═══════════════════════════════════════════
  // HISTORIQUE / SAMOURAÏ
  // ═══════════════════════════════════════════
  { name: "Rurouni Kenshin: Trust", slug: "nobuhiro-watsuki-2", mangaka: "Nobuhiro Watsuki", desc: "Style samouraï mélancolique : croix, regret, ère Meiji", prompt: "rurouni kenshin trust manga style, meiji melancholic, {prompt}, battousai, cross scar, regret, oath", neg: "comedy, modern", tags: ["historical", "samurai", "melancholic"] },
  { name: "Samurai Executioner", slug: "kazuo-koike-2", mangaka: "Kazuo Koike", desc: "Style exécuteur : shogunat, sabre, justice, Edo", prompt: "samurai executioner manga style by kazuo koike, executioner, {prompt}, kubo, edo, justice, sword", neg: "fantasy, modern", tags: ["historical", "samurai", "dark"] },
  { name: "Shigurui", slug: "takayuki-yamaguchi", mangaka: "Takayuki Yamaguchi", desc: "Style sabre brutal : tournoi, sang, duel à mort", prompt: "shigurui manga style by takayuki yamaguchi, brutal sword, {prompt}, kogan, tournament, death match, blood", neg: "bright, clean", tags: ["historical", "samurai", "brutal"] },
  { name: "Kaze Hikaru", slug: "taeko-watanabe", mangaka: "Taeko Watanabe", desc: "Style shinsengumi : femme samouraï, romance historique", prompt: "kaze hikaru manga style by taeko watanabe, shinsengumi historical, {prompt}, female samurai, bakumatsu, romance", neg: "modern, fantasy", tags: ["historical", "shojo", "samurai"] },
  { name: "Historie", slug: "hitoshi-iwaaki-2", mangaka: "Hitoshi Iwaaki", desc: "Style Grèce antique : Alexandre, stratégie, époque hellénistique", prompt: "historie manga style by hitoshi iwaaki, ancient greece, {prompt}, alexander, eumenes, hellenistic, historical epic", neg: "fantasy, magic", tags: ["historical", "ancient", "epic"] },
  { name: "Cesare", slug: "soy-joy", mangaka: "Sōryū Fuyumi", desc: "Style Renaissance : Italie, Borgia, politique, art", prompt: "cesare manga style, italian renaissance, {prompt}, borgia, florence, da vinci, political intrigue, historical", neg: "fantasy, action", tags: ["historical", "renaissance", "political"] },
  { name: "Emma", slug: "kaoru-mori", mangaka: "Kaoru Mori", desc: "Style Victorian : domesticité, romance, Angleterre 19e", prompt: "emma manga style by kaoru mori, victorian england, {prompt}, maid, butler, historical romance, detailed dresses", neg: "fantasy, modern", tags: ["historical", "romance", "victorian"] },
  { name: "A Bride's Story", slug: "kaoru-mori-2", mangaka: "Kaoru Mori", desc: "Style Asie centrale : mariage, culture, vie quotidienne détaillée", prompt: "a bride's story manga style by kaoru mori, central asia, {prompt}, bride, silk road, cultural, detailed embroidery", neg: "modern, fantasy", tags: ["historical", "cultural", "detailed"] },

  // ═══════════════════════════════════════════
  // PSYCHOLOGIQUE / DRAME
  // ═══════════════════════════════════════════
  { name: "Death Note", slug: "tsugumi-oba", mangaka: "Tsugumi Ohba", desc: "Style mystérieux : shinigami, stratégie, thriller psychologique", prompt: "death note manga style by tsugumi ohba, psychological thriller, {prompt}, death note, shinigami, light, L, cat and mouse", neg: "action, comedy", tags: ["psychological", "thriller", "mystery"] },
  { name: "Monster", slug: "naoki-urasawa-m", mangaka: "Naoki Urasawa", desc: "Style hôpital : chirurgien, tueur en série, Allemagne", prompt: "monster manga style by naoki urasawa, hospital thriller, {prompt}, tenma, johan, germany, serial killer, suspense", neg: "fantasy, action", tags: ["psychological", "thriller", "hospital"] },
  { name: "Liar Game", slug: "shinobu-kaitani", mangaka: "Shinobu Kaitani", desc: "Style jeux d'esprit : tromperie, bluffs, argent", prompt: "liar game manga style by shinobu kaitani, psychological game, {prompt}, deception, bluff, money, tournament", neg: "action, fantasy", tags: ["psychological", "thriller", "game"] },
  { name: "Kaiji", slug: "nobuyuki-fukumoto", mangaka: "Nobuyuki Fukumoto", desc: "Style jeu d'argent : dettes, survie, désespoir, stratégie", prompt: "kaiji manga style by nobuyuki fukumoto, gambling despair, {prompt}, debt, survival, strategy, desperation, unique art", neg: "clean, modern", tags: ["psychological", "gambling", "despair"] },
  { name: "The Flowers of Evil", slug: "shuzo-oshiro", mangaka: "Shuzo Oshiro", desc: "Style rotoscopique : adolescence, perversion, Baudelaire, réaliste", prompt: "flowers of evil manga style by shuzo oshiro, rotoscoped realistic, {prompt}, adolescence, baudelaire, perversion, provincial", neg: "cartoon, anime style", tags: ["psychological", "dark", "realistic"] },
  { name: "Oyasumi Punpun", slug: "inzio-asano", mangaka: "Inio Asano", desc: "Style existentiel : oiseau dépressif, vie, tristesse, espoir", prompt: "oyasumi punpun manga style by inio asano, existential depression, {prompt}, punpun, bird, life sadness, hope", neg: "happy, bright", tags: ["psychological", "existential", "dark"] },
  { name: "Solanin", slug: "inzio-asano-2", mangaka: "Inio Asano", desc: "Style jeune adulte : musique, travail, doute, vingtaine", prompt: "solanin manga style by inio asano, young adult, {prompt}, rock band, graduation, uncertainty, twenties, slice of life", neg: "fantasy, action", tags: ["psychological", "slice of life", "music"] },
  { name: "Goodnight Punpun", slug: "inzio-asano-3", mangaka: "Inio Asano", desc: "Style enfance difficile : traumatisme, croissance, réalisme sale", prompt: "goodnight punpun manga style by inio asano, childhood trauma, {prompt}, growing up, gritty realism, depression", neg: "clean, anime style", tags: ["psychological", "dark", "childhood"] },
  { name: "Aku no Hana", slug: "shuzo-oshiro-2", mangaka: "Shuzo Oshiro", desc: "Style perversion adolescente : rotoscopie, obsession, culpabilité", prompt: "aku no hana manga style by shuzo oshiro, rotoscoped, {prompt}, teenage perversion, obsession, guilt, realistic", neg: "anime style", tags: ["psychological", "dark", "realistic"] },
  { name: "Boys on the Run", slug: "kano-yasuhiro", mangaka: "Kanō Yasuhiro", desc: "Style loser attachant : boxe, emploi, relations, raté", prompt: "boys on the run manga style, loser boxing, {prompt}, employment, relationships, failure, determination", neg: "fantasy, perfect", tags: ["psychological", "comedy", "sports"] },

  // ═══════════════════════════════════════════
  // COMÉDIE
  // ═══════════════════════════════════════════
  { name: "Grand Blue", slug: "kenji-inoue", mangaka: "Kenji Inoue", desc: "Style comédie plongée : alcool, fac, muscles, fraternité", prompt: "grand blue manga style by kenji inoue, diving comedy, {prompt}, college, alcohol, muscle, peer pressure, hilarious", neg: "serious, dark", tags: ["comedy", "slice of life", "college"] },
  { name: "Prison School", slug: "akira-hiramoto", mangaka: "Akira Hiramoto", desc: "Style comédie prison : école, punition, absurdité, ecchi", prompt: "prison school manga style by akira hiramoto, prison comedy, {prompt}, school punishment, absurd, ecchi, hilarious", neg: "normal, serious", tags: ["comedy", "ecchi", "school"] },
  { name: "GTO", slug: "toru-fujisawa", mangaka: "Toru Fujisawa", desc: "Style prof délinquant : moto, enseignement, 90s, badass", prompt: "gto manga style by toru fujisawa, teacher delinquent, {prompt}, onizuka, high school, 90s, comedy, great teacher", neg: "modern, serious", tags: ["comedy", "school", "90s"] },
  { name: "Nichijou", slug: "keiichi-ara", mangaka: "Keiichi Arawi", desc: "Style quotidien absurde : explosions, école, délires, mignon", prompt: "nichijou manga style by keiichi aravi, absurd daily life, {prompt}, school, explosion, hakase, nano, quirky", neg: "normal, serious", tags: ["comedy", "absurd", "cute"] },
  { name: "Daily Lives of High School Boys", slug: "yasunobu-yamauchi", mangaka: "Yasunobu Yamauchi", desc: "Style quotidien lycéen : amis, jeux, rôle, humour", prompt: "daily lives of high school boys manga style, school boy comedy, {prompt}, friendship, role play, everyday humor", neg: "dark, serious", tags: ["comedy", "school", "slice of life"] },
  { name: "Detroit Metal City", slug: "kiminori-wakasugi", mangaka: "Kiminori Wakasugi", desc: "Style metal comique : death metal, alter ego, musique extrême", prompt: "detroit metal city manga style, death metal comedy, {prompt}, krauser, DMC, extreme music, split personality", neg: "normal, clean", tags: ["comedy", "music", "absurd"] },
  { name: "The Way of the Househusband", slug: "kousuke-o", mangaka: "Kousuke Oono", desc: "Style yakuza ménager : ex-yakuza, cuisine, vie quotidienne", prompt: "way of the househusband manga style by kousuke oono, yakuza househusband, {prompt}, cooking, cleaning, former yakuza, comedy", neg: "serious, dark", tags: ["comedy", "slice of life", "yakuza"] },
  { name: "Hinamatsuri", slug: "masao-ohira", mangaka: "Masao Ohtake", desc: "Style psychique comique : pouvoirs, famille, yakuza, délire", prompt: "hinamatsuri manga style by masao ohtake, psychic comedy, {prompt}, hina, telekinesis, yakuza, found family", neg: "dark, serious", tags: ["comedy", "supernatural", "slice of life"] },
  { name: "Saiki K", slug: "shuichi-aso", mangaka: "Shuichi Aso", desc: "Style psy blasé : télépathe, école, cacher ses pouvoirs", prompt: "saiki k manga style by shuichi aso, psychic comedy, {prompt}, saiki, telepathy, school, hiding powers, deadpan", neg: "dramatic, serious", tags: ["comedy", "supernatural", "school"] },

  // ═══════════════════════════════════════════
  // MARTIAL ARTS / COMBAT
  // ═══════════════════════════════════════════
  { name: "Kengan Ashura", slug: "yabako-sandrovich", mangaka: "Yabako Sandrovich", desc: "Style combat brutal : arts martiaux, tournoi, muscles déchirés", prompt: "kengan ashura manga style, brutal martial arts, {prompt}, kengan tournament, ohma, intense fighting, muscular", neg: "fantasy, magical", tags: ["martial arts", "brutal", "tournament"] },
  { name: "Baki the Grappler", slug: "keisuke-itagaki", mangaka: "Keisuke Itagaki", desc: "Style combat surhumain : muscles, prison, arts martiaux extrêmes", prompt: "baki manga style by keisuke itagaki, extreme martial arts, {prompt}, baki, yujiro, prison, superhuman, muscles", neg: "fantasy, magic", tags: ["martial arts", "extreme", "brutal"] },
  { name: "Holyland", slug: "mori-kouji", mangaka: "Mori Kouji", desc: "Style survival street : combat de rue, SDF, apprentissage", prompt: "holyland manga style by mori kouji, street fighting, {prompt}, survival, homeless, learning, realistic martial arts", neg: "fantasy, supernatural", tags: ["martial arts", "street", "realistic"] },
  { name: "All Rounder Meguru", slug: "hiroshi-matsumoto", mangaka: "Hiroshi Matsumoto", desc: "Style MMA réaliste : arts martiaux mixtes, cage, technique", prompt: "all rounder meguru manga style by hiroshi matsutomo, mma realistic, {prompt}, mixed martial arts, cage fighting, technique", neg: "supernatural, action", tags: ["martial arts", "mma", "realistic"] },
  { name: "History's Strongest Disciple Kenichi", slug: "syun-matsuena", mangaka: "Syun Matsuena", desc: "Style disciple : maîtres, entraînement extrême, combat", prompt: "kenichi manga style by syun matsuena, martial arts master, {prompt}, disciple, training, ryouzanpaku, masters", neg: "fantasy, horror", tags: ["martial arts", "comedy", "training"] },
  { name: "The Breaker", slug: "jeon-keuk-jin", mangaka: "Jeon Keuk-jin", desc: "Style murim coréen : arts martiaux, école, pouvoir caché", prompt: "the breaker manga style by jeon keuk-jin, murim korean, {prompt}, martial arts, school, hidden power, sunwoo", neg: "fantasy, magic", tags: ["martial arts", "manhwa", "murim"] },

  // ═══════════════════════════════════════════
  // CULTE / INDÉ
  // ═══════════════════════════════════════════
  { name: "Catsby", slug: "kazuya-minagawa", mangaka: "Kazuya Minagawa", desc: "Style surréaliste : chat, moto, drogue, néon, délire", prompt: "catsby manga style, surreal cat, {prompt}, motorcycle, drugs, neon, psychedelic, underground", neg: "normal, clean", tags: ["cult", "surreal", "underground"] },
  { name: "Dorohedoro", slug: "q-hayashi", mangaka: "Q Hayashida", desc: "Style post-apo crasseux : magie noire, reptiles, masques de gaz", prompt: "dorohedoro manga style by q hayashida, grunge post-apocalyptic, {prompt}, hole, magic, reptile, gas mask, gore", neg: "clean, bright", tags: ["cult", "post-apocalyptic", "dark"], h: 768 },
  { name: "Witch Hat Atelier", slug: "kamome-shirahama", mangaka: "Kamome Shirahama", desc: "Style magie détaillé : sorcières, chapeaux, grimoires, dessin précis", prompt: "witch hat atelier manga style by kamome shirahama, detailed witch, {prompt}, hat, grimoire, magic circles, european", neg: "modern, digital flat", tags: ["fantasy", "magic", "detailed"] },
  { name: "Land of the Lustrous", slug: "haruko-ichikawa", mangaka: "Haruko Ichikawa", desc: "Style gemmes : cristaux, androgynes, corps brisés, philosophie", prompt: "land of the lustrous manga style by haruko ichikawa, gem crystal, {prompt}, phos, gem, broken body, philosophical", neg: "human proportions, realistic", tags: ["cult", "philosophical", "unique"] },
  { name: "Girls' Last Tour", slug: "tsukumizu", mangaka: "Tsukumizu", desc: "Style post-apo mignon : fin du monde, filles, moto, silence", prompt: "girls last tour manga style by tsukumizu, post-apocalyptic cute, {prompt}, chito, yuuri, kettenkrad, silence, world end", neg: "action, horror", tags: ["cult", "post-apocalyptic", "cute"] },
  { name: "Houseki no Kuni", slug: "haruko-ichikawa-2", mangaka: "Haruko Ichikawa", desc: "Style gemmes combat : cristaux, lune, bouddhisme, dissolution", prompt: "houseki no kuni manga style by haruko ichikawa, gem fighting, {prompt}, crystal, moon, buddhism, dissolution, beautiful", neg: "realistic, human", tags: ["cult", "philosophical", "beautiful"] },
];

// Générer SQL
function generateSQL(): string {
  const lines: string[] = [
    `-- Seed: ${STYLES.length} styles manga pour l'entraînement IA`,
    `-- Généré le ${new Date().toISOString()}`,
    "",
    "INSERT INTO ai_manga_styles (name, slug, mangaka, description, model_version, prompt_template, negative_prompt, width, height, style_tags, training_status) VALUES",
  ];

  for (let i = 0; i < STYLES.length; i++) {
    const s = STYLES[i];
    const h = s.h ?? H_DEFAULT;
    const tags = s.tags.map((t) => `'${t}'`).join(", ");
    const comma = i < STYLES.length - 1 ? "," : "";

    lines.push(`  ('${s.name}', '${s.slug}', '${s.mangaka}', '${s.desc}', ${MODEL}, '${s.prompt}', '${s.neg}', ${W}, ${h}, ARRAY[${tags}], 'ready')${comma}`);
  }

  lines.push("");
  lines.push("ON CONFLICT (slug) DO UPDATE SET");
  lines.push("  prompt_template = EXCLUDED.prompt_template,");
  lines.push("  negative_prompt = EXCLUDED.negative_prompt,");
  lines.push("  style_tags = EXCLUDED.style_tags;");
  lines.push("");
  lines.push(`-- ${STYLES.length} styles insérés`);

  return lines.join("\n");
}

// Écrire le fichier SQL
const sql = generateSQL();
const path = "database/seed-manga-100plus.sql";
Deno.writeTextFileSync(path, sql);
console.log(`✅ Fichier généré : ${path} (${STYLES.length} styles)`);
console.log(`📂 Copie le contenu dans Supabase SQL Editor`);
